name: Test reverse dependencies
on:
  pull_request:
  workflow_dispatch:
jobs:
  reverse_dependencies:
    name: Reverse dependency testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: martinfleis/reverse-dependency-testing@verbose
        with:
            package_name: libpysal
            ignore: >-
              fine
              tigernet
              cenpy
              autoesda
            include: mapclassify
            install: >-
                setuptools-scm
            fail_on_failure: false
            verbose: true
