name: Test reverse dependencies
on:
  pull_request:
  workflow_dispatch:
jobs:
  reverse_dependencies:
    name: Reverse dependency testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: martinfleis/reverse-dependency-testing@verbose
        with:
            package_name: libpysal
            ignore: >-
              fine
              tigernet
              cenpy
              autoesda
              region
            include: >-
              mapclassify
              libpysal
            whitelist: >-
              esda
              spreg
              spaghetti
            install: >-
              setuptools-scm
              py-opencv
              h3-py
              hdbscan
              pandana
              astropy
            install_pip: >-
              opencv-contrib-python
              KDEpy
            installation_command: >-
              pip install .; python -c 'import libpysal; libpysal.examples.fetch_all()'
            fail_on_failure: false
            verbose: true
            parallel: false
