on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           environment-file: ci/travis/36-latest-conda-forge.yaml
           python-version: 3.6
           auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
